### ISSUE TITLE
Linkscape crashes at 3.-4. resolution

### ISSUE THREAD

**Issue by rollerjunge** [AccentuSoft/LinkScope_Client#14]
In addition to issue #13 Linkscope crashes with an empty error message usually after 3 or 4 resolutions. Again, latest portable Linkscope on Windows 11

![2022-03-05 14_46_05-](https://user-images.githubusercontent.com/34043908/156886015-bf2346df-b2c7-4468-8948-e795381677cd.png)

**Comment by AccentuSoft** [comment]
The 'sfdp' layout option is not available on Windows due to the library that facilitates it being Linux only.

Please select 'neato' or 'dot' for the GraphLayout option in the Program Settings, and let me know if the problem persists:

File -> Edit Settings -> Program Settings -> 'GraphLayout' -> 'neato' or 'dot'.

**Comment by rollerjunge** [comment]
dot is selected. Buit this may be because I installed afterwards uusing the installer version. Dunno whether both versions share the same settings? Nevertheless, now it is not happening any more.

**Comment by rollerjunge** [comment]
BTW, thanks for the fast replies. The software looks promising If you manage to provide an open and free alternative to maltego this would be awesome.  In Maltego, i miss the possibility of an exchange of user generated transforms most. Would be glad to see something like that here. And it yould give you the possibility for several more resolutions without coding them all yourself.
